### ISSUE TITLE
Replan cmake lectures

### ISSUE THREAD

**Issue by uekerman** [Simulation-Software-Engineering/Lecture-Material#55]
We needed a bit more time as planned:

- Env Var, Paths, Libs, and how to use them: took 30 mins without going into tooo much detail, and without pkg-config etc
- Introduction to Make: took 15 mins
- Introduction to CMake: took 75 mins, with short part on preCICE `CMakeLists.txt`, without CPack

**Comment by LarissaBrencher** [comment]
Small feedback on last week's exercise sheet about CMake etc:
I found it hard to identify the tasks on the last exercise sheet because its structure seems to differ a lot from the last exercise sheets. I read the whole sheet first, but didn't understand at first what the actual "smaller" steps are in order to achieve the overall task. 
I think it might be helpful (just an idea), if it was split up into sub-tasks. For example go into more detail for including one of the main.cpp's dependencies, i.e. 
1. uncomment in main.cpp, 
2. install required package, 
3. add corresponding command to CMakeLists.txt, 
4. try if it builds and runs, 
5. if yes, then add to Dockerfile,
6. repeat for all other dependencies accordingly.

Another remark I have regarding the lecture material: I think it would help to include some kind of overview of the most important commands for editing a CMakeLists.txt like in the previous lectures for e.g. Docker. Maybe this would already clarify the exercise without changing the current exercise sheet. (Or maybe it was just me who struggled with last week's learning contents. I just thought I should let you know as you already opened up an issue about replaning this part of the lecture.)
